### ISSUE TITLE
Overscoring is possible

### ISSUE THREAD

**Issue by MomoMiles** [SchwaIndustries/ScrimBot#10]
**Describe the bug**
You can score a match that is already completed

**To Reproduce**
1: Create a match
2: Score a match
3: Score a match again

**Expected behavior**
The bot will notice you scored already and prevent.

**Bot Version**
1.2.1

**Additional context**
Could be fixed by allowing match edit **AFTER** match has been scored. More admin control clearly needed.

**Comment by Kalissaac** [comment]
Does this overwrite the score in the database with the new one or are two scores created inside?

**Comment by Kalissaac** [comment]
Yes it does, the PR should fix this.
