### ISSUE TITLE
Icebox Match Thumbnail

### ISSUE THREAD

**Issue by Kalissaac** [SchwaIndustries/ScrimBot#17]
Does Riot not provide a minimap for new maps anymore? I couldn't find one for Icebox like there is for the other maps.

[Here's the one for Split](https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt2caea7a88362d6aa/5ecd64b0817e574fa1dcc162/split-minimap-2.png), nothing similar exists for Icebox that I've seen. (Even if you replace "split" in the URL with "icebox.")

**Comment by MomoMiles** [comment]
[Here's](https://preview.redd.it/sc2cvp60ukr51.jpg?width=3000&format=pjpg&auto=webp&s=efddb43399d680842e1ec85a7a87a174abf048f6) the best I found

**Comment by MomoMiles** [comment]
or this? 
![image](https://user-images.githubusercontent.com/29339065/97375881-2f621a80-1879-11eb-9c70-dffaaeff14c5.png)

**Comment by Kalissaac** [comment]
Is the second image a screenshot? If so, then I think we'll go with the first one for now, it looks close enough to the style of the other images.
