### ISSUE TITLE
Match Reactions Stop Working

### ISSUE THREAD

**Issue by Kalissaac** [SchwaIndustries/ScrimBot#18]
**Describe the bug**
After an unknown event, the reactions to join a team do not respond. Any new matches created work fine.

**To Reproduce**
1. ???
2. React to a team on a match message
3. Nothing happens

**Expected behavior**
The bot should add the player to the team.

**Bot Version**
v1.3.0

**Comment by MomoMiles** [comment]
Issue self resolved. Too little information to continue the investigation. Please reopen the ticket if the issue arises again
