### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by Rehkloos** [SchwaIndustries/ScrimBot#26]
**Describe the bug**

**To Reproduce**
just run the bot

```
E:\Programs\gitrepos\ScrimBot\src\services\matchCreation.js:77
        matchRecord.creationInformation.map = CONSTANTS.MAPS.find(e => e === content) ?? content
                                                                                       ^

SyntaxError: Unexpected token ?
```

**Expected behavior**

**Bot Version**
1.4.0

**Screenshots**

**Additional context**

**Comment by Kalissaac** [comment]
Hi, could you try using Node 14 or greater and let me know if that works?

**Comment by Rehkloos** [comment]
> Hi, could you try using Node 14 or greater and let me know if that works?

that did the trick
now getting 
```
Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.
```

**Comment by Kalissaac** [comment]
Do you have a line or any type of stacktrace for that? Does it happen when the bot starts up or is it when a specific command is run?
