### ISSUE TITLE
Incorrect Match Score command doesn't delete

### ISSUE THREAD

**Issue by MomoMiles** [SchwaIndustries/ScrimBot#28]
**Describe the bug**

When you enter the v!match score command incorrectly, it doesn't delete the message telling you that you entered it wrong

**To Reproduce**
1. Do `v!match score 13-8` (missing match ID)
2. See bot error message

**Expected behavior**
Error message should delete eventually

**Bot Version**
Can be found by running v!version.
1.5.0

**Comment by Kalissaac** [comment]
Intended behavior. `v!match score` and `v!match edit` among others don't delete messages. Maybe we want to standardize the behavior later on, but this isn't a priority right now.
