### ISSUE TITLE
"Any min" and "any max" can be chosen as ranks

### ISSUE THREAD

**Issue by Kalissaac** [SchwaIndustries/ScrimBot#6]
**Describe the bug**
Users are able to select "any min" and "any max" as their VALORANT competitive rank in the bot. This is due to the fact that those ranks are added to CONSTANTS.js for match creation, where you have the ability to select rank minimums and maximums for matches.

**To Reproduce**
1. Run the command `v!user edit rank any min` or `v!user edit rank any max` OR when selecting a rank through the registration process
2. It will cause an error when the bot attempts to give you the appropriate rank role in servers

**Expected behavior**
Those "ranks" should not be able to be selected.

**Bot Version**
v1.0.0

**Comment by Kalissaac** [comment]
Fixing this would either require checks when a rank is changed, or modifying the match rank minimum and maximum selection. Is this important enough to dedicate time to?

**Comment by Kalissaac** [comment]
So it looks like "any min" is indeed deemed invalid by the bot, but "any max" works? No idea as to the reason for the discrepancy.

**Comment by MomoMiles** [comment]
Difficult to fix, and really causes no issue... Just don't pick any min or any max when assigning a rank?

**Comment by Kalissaac** [comment]
That's not really the solution to this problem..

**Comment by MomoMiles** [comment]
Fine, I'll deal with it later. Not high priority though.
