### ISSUE TITLE
How to assign a user as bot admin?

### ISSUE THREAD

**Issue by bhainovi** [SchwaIndustries/ScrimBot#8]
**Describe the bug**
Whenever I fire the command "v!restart" the bot response is "This command can only be executed by bot admins."
 
**To Reproduce**
Type command "v!restart"

**Expected behavior**
The bot should have restarted since I have the admin role

**Bot Version**
1.0.0

**Comment by MomoMiles** [comment]
To assign a user as admin, create a collection in your database called "botAdmins"

Within this collection, add a document named the userID of the user that you wish to be a botAdmin. The document content can be empty. Hopefully this helps :)

**Comment by bhainovi** [comment]
> To assign a user as admin, create a collection in your database called "botAdmins"
> 
> Within this collection, add a document named the userID of the user that you wish to be a botAdmin. The document content can be empty. Hopefully this helps :)
> 
> If you need more assistance, feel free to message reply here.

Hey, This worked perfectly. Thanks for the prompt response!

**Comment by MomoMiles** [comment]
No worries, glad to help. Thanks for using scrimbot :)
